------------------------------
-------- Urheberrecht --------
------- by [LA]Leyynen -------
------------ 2012 ------------
------------------------------
---- Script by Noneatme ------

handy_help_titel = {
	[1] = "Wie verdiene ich Geld ?",
	[2] = "Wie kaufe ich ein Auto ?",
	[3] = "Was kann ich mit Geld machen ?",
	[4] = "Wie werde ich Fraktionsmitglied ?",
	[5] = "Kann mein Auto kaputt gehen ?",
	[6] = "Was fuer Fraktionen gibt es ?",
	[7] = "Wo finde ich die Regeln ?",
	[8] = "Wie lautet das Forum ?",
	[9] = "Wo kann ich Waffen kaufen ?",
	[10] = "Wo finde ich die Stadthalle ?",
	[11] = "Wo kann ich einen Fuehrerschein machen ?",
	[12] = "Wie kann ich Hilfe rufen ?",
	[13] = "Wie schliesse ich mein Handy ?",
	[14] = "Wie lautet die Teamspeak Adresse ?",
	[15] = "Ich moechte gerne Spenden !",
	[16] = "Jemand hat mich grundlos getoetet !",
	[17] = "Ich habe ein Bug / Fehler entdeckt !",
	[18] = "Ich habe ein gute Idee / Vorschlag !",
	[19] = "Mein Auto ist einfach so explodiert !",
	[20] = "Wie kann ich mein Auto abschliessen ?",
	[21] = "Wie starte ich einen Motor ?",
	[22] = "Wie wird jemand entbannt ?",
	[23] = "Wie sehe ich mein Geld ?",
	[24] = "Wie mache ich ein Screenshot ?",
	[25] = "Wie repariere ich mein Fahrzeug ?",
	[26] = "Wie bestelle ich mir eine Pizza ?", 
	[27] = "Wie ueberweise ich jemanden Geld ?",
	[28] = "Wie bediene ich den Gabelstabler ?",
	[29] = "Wie werden meine Waffenskills Hitman ?",
	[30] = "Wo ist der Bahnhof ?",
	[31] = "Wie wird man Reporter ?",
    [32] = "Wie kann ich mich am besten fuer eine Fraktion bewerben ?",
    [33] = "Was passiert wenn ich meine Fraktionsbewerbung abgeschickt habe ?",
    [34] = "Warum sucht die Polizei nach mir ?",
    [35] = "Warum bin ich im Knast ?",
    [36] = "Was ist ein Biz und wie bekomme ich so was ?",
    [37] = "Wo kann ich feiern ?",
    [38] = "Was kann ich unter den Events der LTR verstehen ?",
    [39] = "Wie kann ich mein Aussehen aendern (Skin) ?",
    [40] = "Wie kann ich mein Auto tunen ?",
    [41] = "Was macht der Medic ?",
    [42] = "Wie funktioniert das Handy-Radio ?",
    [43] = "Ich verstehe die Abkuerzungen von andern Spielern nicht !",
    [44] = "Mein Auto raucht schwarz und faehrt nicht mehr ?",
    [45] = "Was macht der Mechaniker ?",
    [46] = "Warum stehen ueberall Muelltonnen rum ?",
}


handy_help_text = {
	[1] = "Du verdienst Geld, indem du arbeiten gehst, in einer Fraktion bist, und Paydays bekommst. Paydays bekommst du jede volle Stunde.",
	[2] = "An jeder Position, wo sich ein Auto-Icon auf deiner Minimap befindet, ist ein Autohaus. Gehe dazu in das Dollar-Symbol und du kannst dir die Fahrzeuge ansehen.",
	[3] = "Du kannst mit Geld Fahreuge, Haeuser, Firmen, Prestige-Objekte, Essen, Trinken, Waffen und vieles mehr kaufen.",
	[4] = "Indem du dich im Forum freischalten laesst, und eine Bewerbung in dem entsprechenden Bereich der Fraktion schreibst. Dafuer existiert meist eine Vorlage.",
	[5] = "Dein Fahrzeug kann nicht explodieren, sondern nur einen Totalschaden erleiden. Dann musst du es zu einem Mechaniker bringen.",
	[6] = "Es gibt die Staatsfraktionen (LAPD, FBI, Army), die neutralen Fraktionen (LTR, Emergency), und die boesen Fraktionen.(Compton Families, Watt Soldiers, Yakuza und Camorra)",
	[7] = "Die Regeln findest du im Forum unter 'Regeln'.",
	[8] = "Die Forumadresse lautet: www.la-rl.com",
	[9] = "Du kannst Waffen im Ammu-Nation Shop kaufen, welche in ganz San Andreas verteilt sind. Ausserdem kannst du Waffen per Internet bestellen.(1)",
	[10] = "Eine Stadthalle gibt es hier nicht. Beim Arbeitsamt kannst du Jobs betrachten, die dir zur Verfuegung stehen.",
	[11] = "Scheine kannst du in der Fahrschule machen. Die Fahrschule steht etwas weiter weg vom Bahnhof.",
	[12] = "Du kannst ein Admin kontaktieren, indem du /kontakt [TEXT] eingibst. Ein Admin wird dir dann - sobald er Zeit hat - Helfen.",
	[13] = "Indem du nochmal die Taste drueckst, mit der du das Handy geoeffnet hast.",
	[14] = "Du kannst auf dem Teamspeaksever connecten, indem du die IP 'ts.la-rl.com' eingibst und auf 'Connect' klickst.",
	[15] = "Wenn du Spenden moechtest, kannst du dich an den Inhaber, [LA]Leyynen, wenden. Am besten erreichst du ihn ueber Teamspeak, indem du dich in den Warteraum begibst.",
	[16] = "Dies kann passieren. Wenn du ein Screenshot vom Tatgeschehen machst, kannst du eine Beschwerde im Forum gegen die Person schreiben. Ein Admin wird dann, wenn die Beschwerde berechtigt ist, den User bestrafen.",
	[17] = "Wir moechten dich darauf hinweisen, dass jedem Fehler passieren, und wir oftmals gar nicht Schuld daran haben, da Bugs auch von alleine entstehen koennen. Solltest du ein Bug entdeckt haben, waere es besser, ihn im Forum zu Posten. Wir werden dann versuchen, ihn bei spaeteren Updates zu beheben.",
	[18] = "Solltest du Vorschlaege oder Ideen haben, so kannst du gerne mitwirken und deinen Vorschlag im Forum bekannt geben. Wir werden bei jeder Adminbesprechung die Vorschlaege durchgehen.",
	[19] = "Solltest du der Annahme sein, dass ein Auto von dir durch ein Bug / andere User zerstoert wurde, so kannst du im Forum eine Ersetzungsanfrage schreiben. Ein Admin wird dann die Anfrage bearbeiten. Solltest du selber dein Auto kaputt gemacht haben, wird es nicht ersetzt.",
	[20] = "Du kannst dein Auto abschliessen, indem du mit /fahrzeuge die Slot-ID von deinem Fahrzeug bekommst, und darauf /lock SLOT-ID eingibst. Die SLOT-ID entspricht das Fahrzeug, was du auf / abschliessen moechtest.",
	[21] = "Du kannst den Motor starten, indem du 'X' drueckst. Wiederhole 'X', um den Motor wieder auszumachen. Du kannst mit 'L' das Licht deines Fahrzeuges an/ausschalten.",
	[22] = "Falls eine gewisse Person von einem Admin gebannt wurde, kann er eine Entbannungsanfrage im Forum schreiben. Wenn er die Vorlage ausgefuellt hat, wird es spaeter von den Admins angeschaut. Die entscheiden dann, ob die gebannte Person wieder entbannt wird.",
	[23] = "Um dein Handgeld zu sehen, musst du 'B' druecken. Mit /self -> Status kannst du auch deine Statistiken und dein Bankgeld sehen.",
	[24] = "Um ein Screenshot zu machen, druecke die F12 Taste. Wenn du deine Screenshot Taste in den MTA-Einstellungen geaendert hast, musst du dort draufdruecken, wo du sie verschoben hast. Deine Screenshots werden in deinem MTA ordner unter /screenshots als .png Datei abgespeichert.",
	[25] = "Indem du in einem Pay'n'spray Laden faehrst, oder zu einem Mechaniker gehst, der dir dann so dein Auto guenstiger repariert.",
	[26] = "Indem du im Browser auf www.pizza.com gehst und eine Pizza bestellst, oder unter 'loogle Places' auf der Startseite des Browsers auf das Bild mit dem Inhalt 'Well Stacked Pizza Co.' klickst, und dort bestellst.",
	[27] = "Du kannst im Browser auf das Bild unterhalb des 'loogle places' Bild auf der Startseite klicken, und dort auf das 'Bank of San Andreas' Bild klickst. Du kannst dort dann die Summe und den Spielername eingeben, zu dem du das Geld ueberweisen moechtest. Du kannst dir ausserdem auch Geld zu deiner Position liefern lassen, indem du auf 'Geld per Luftpost senden' klickst.",
	[28] = "Um die Zinken nach unten zu machen, musst du num_2 druecken. Um sie nach oben zu machen, druecke num_8. Wenn du die Einstellungen veraendert hast oder sie nicht funktionieren, musst du selber nachschauen!",
	[29] = "Um das Hitmanlevel der Waffen zu erreichen, musst du 2x mit der Waffe im Ammu Nation in San Fierro trainieren. Wenn du die 2 Level mit mehr als 90 Prozent erreicht hast, hast du bei der Waffe automatisch das Hitman level.",
	[30] = "Der Bahnhof befindet sich in Doherty, in San Fierro. Gegenueber befindet sich das Wang-Cars Autohaus, wo auch ein Pay'n'spray zu finden ist.",
	[31] = "Reporter gehoeren einer Fraktion an, die Liberty Tree Redaction heisst. Dafuer musst du dich auch im Forum bewerben.",
    [32] = "Jede Fraktion hat ihre eigene Bewerbungsvorlage die dir Hilft, leicht in eine Fraktion zu kommen.",
    [33] = "Die Fraktionsmitglieder und der Leader schauen sie sich an und bewerten sie, z.B: Ob du dich an die Vorgaben gehalten hast, ob du die noetigen Voraussetzungen hast oder ob du schon einmal negativ aufgefallen bist. Was du auf keinen Fall tuen darfst, ist auf deine Bewerbung aufmerksam machen. Die Fraktion wird es sicherlich lesen.",
    [34] = "Du hast anscheinend was illegales gemacht. Das geht von urinieren [/piss] in der Oeffentlichkeit bis hin zu Massenmord. Rechts oben erscheinen dunkelgelbe Sterne, sogenannte Wanteds. Man kann max. 6 bekommen. Je mehr von denen, desto laenger sitzt du im Knast. Bei 1-3 Wanteds ist die Polizei fuer dich zustaendig, bei 4-5 kommt das FBI und bei 6 Wanteds kommt die Los Angeles Army und hat die direkte Erlaubnis dich zu toeten.",
    [35] = "Du hast dich entweder im Polizeirevier gestellt und wurdest auf Kaution eingesperrt, wurdest von Polizei o.a. verhaftet und eingesperrt oder du wurdest aufgrund der Sicherheit K.O. geschossen. Mit /knastzeit kannst du sehn wie lange du noch eingesperrt bist und wenn du Kaution hast kannst du mit /bail dich rauskaufen. Bei /bail geht der Preis vom Bargeld ab.",
    [36] = "Ein Biz ist sowas wie ein kleines Geschaeft mit dem man aber viel Geld verdienen kann. Mann kann nur ein Biz kaufen wenn eins frei ist. Es gibt sehr viele verschiedene Biz, am besten suchst du in SF nach den Hauptshops.",
    [37] = "Partymoeglichkeiten gibt es genug in LA. Wir haben das in Battery Point sitzende Jizzys und wem es da nicht gefaellt, der kann noch auf die andere Uferseite, um genau zu sein zur Gaydar Station wo Man(n) herzlich willkommen ist.",
    [38] = "Die LTR macht fast taeglich Events um ein bisschen Spass zu dir und deinem Geldbeutel zubringen. Vom Suchevent ueber Wettrennen bis zum TeamDeathMatch ist alles dabei.",
    [39] = "In Financial gibt es den Skinladen Zip. Wenn du da rein gehst kannst du einen von mehr als 100 Skins, sowohl Mann als auch Frau auswaehlen. Einige Skins bekommt man nur wenn man in einer bestimmten Fraktion ist.",
    [40] = "Noerdlich vom Bahnhof gibt es die Tuning-Garage. Wenn du da mit einem deiner Autos reinfaehrst, siehst du was an deinem Auto getunet werden kann. Ausserdem kann man bei den Mechanikern in City Hall dir einen Sportmotor einbauen lassen fuer kleines Geld.",
    [41] = "Die Medics sind ein Teil der Los Angeles Emergency. Ihre Hauptaufgabe ist es, innerhalb einer Minute zu Opfern hinzufahren/fliegen und diese dann wiederzubelben. Ein Medic kann auch Spieler heilen und ihnen eine halbe Schutzweste geben.",
    [42] = "Wenn du das Handy mit der Taste 1 oeffnest steht in der unteren Haelfte die Radio-App, die klickst du an und gibst links den Namen an wie das Radio heissen soll und eechts eine Livestream URL ein. So eine bekommt man auf den Seiten von Radiosendern im Internet wie z.b Technobase oder BigFM.",
    [43] = "Weil es zu lange dauern wuerde alles auszuschreiben gibt es hier einige Abkuerzungen wie : AFK = Kurz abwesend / Wd = Wieder da . Da fast woechentlich neue hinzukommen fragt euch einfach durch, es gibt keine dummen Fragen.",
    [44] = "Wenn dies der Fall ist, hat dein Auto einen Totalschaden und du musst mit /mechaniker einen Mechaniker rufen. Wenn der dann da ist wird dieser erstmal 1000 Dollar fuer die Reparatur verlangen und dann dein Auto zur Werkstatt abschleppen. In dieser wird es dann auf die Hebebuehne geschoben und dann wieder flott gemacht.",
    [45] = "Die Mechaniker sind ein Teil der Los Angeles Emergency. Ihr Hauptaufgabe ist es Fahrzeuge mit Totalschaden abzuschleppen und sie ihn ihre Base zu bringen, in der die Fahrzeuge dann repariert werden. Ausserdem kann der Mechaniker in dein Auto einen Sportmotor einbauen der den Wagen stark beschleunigen laesst. ",
    [46] = "In jeder Muelltonne koennte etwas sehr interessantes sein. Das kann z.B. Geld, Waffen oder einfach ganz nomaler Muell sein .",
}